debug: true

telegram:
  api-url: https://api.telegram.org/
  webhook-path: https://df0c-46-138-30-102.eu.ngrok.io  # https://api.telegram.org/bot5128213958:AAERMqZfvd5YsTwGRUAnYqsCBHu_2iMR6DM/setWebhook?url=https://4727-46-138-30-102.eu.ngrok.io



server:
  port: 8080
  servlet:
    context-path: /swbot

spring:

  h2:
    console:
      enabled: true
#      settings:
#        web-allow-others: false
  jpa:
    show-sql: true
    properties:
      hibernate:
        #dialect: org.hibernate.dialect.PostgreSQL94Dialect
        dialect: org.hibernate.dialect.H2Dialect

  datasource:
    #driver-class-name: org.postgresql.Driver
    #url: jdbc:postgresql://localhost:5432/postgres?currentSchema=products
    #username: postgres
    #password: pgadmin
    url: jdbc:h2:mem:mydatabase;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: sa
    password: sa


  flyway:
    enabled: false